/**
 * One class per failure mode, and the remedy kept separate from the message:
 * the message says what happened, the remedy is the half a model should act on.
 * `toFailure()` lifts it to a top-level field so it is not buried inside an
 * upstream envelope, where it gets skimmed past.
 */
export class A2AApiError extends Error {
  /** Typed `string`, not the literal, so a subclass can override it. */
  override readonly name: string = "A2AApiError";
  readonly status: number;
  readonly remedy: string | undefined;
  readonly errors: unknown;

  constructor(message: string, opts: { status: number; remedy?: string; errors?: unknown }) {
    super(message);
    this.status = opts.status;
    this.remedy = opts.remedy;
    this.errors = opts.errors;
  }
}

/**
 * The local daemon did not answer. Far and away the most common failure here,
 * and the one whose remedy is least guessable — so it gets its own class and
 * spells out all three causes.
 */
export class DaemonUnreachableError extends A2AApiError {
  override readonly name = "DaemonUnreachableError";

  constructor(daemonUrl: string, cause: unknown) {
    super(`The A2A daemon at ${daemonUrl} did not answer: ${describeCause(cause)}`, {
      status: 0,
      remedy:
        `Start it with \`a2a-serve\` (or \`launchctl kickstart -k gui/$(id -u)/io.mgcrea.mcp-a2a\` ` +
        `if the LaunchAgent is loaded), and check that A2A_DAEMON_URL names the same address ` +
        `the daemon binds. The daemon is a separate process on purpose: an inbound listener has ` +
        `to outlive any one client.`,
    });
  }
}

/** A peer's agent card could not be fetched or did not parse. */
export class PeerUnreachableError extends A2AApiError {
  override readonly name = "PeerUnreachableError";

  constructor(url: string, cause: unknown) {
    super(`Could not read an agent card from ${url}: ${describeCause(cause)}`, {
      status: 0,
      remedy:
        `Check the peer is running and serving /.well-known/agent-card.json at that base URL. ` +
        `Pass the peer's BASE url (http://127.0.0.1:41241), not the card path itself.`,
    });
  }
}

/** A task id that is not ours, or not a legal store key. */
export class TaskNotFoundError extends A2AApiError {
  override readonly name = "TaskNotFoundError";

  constructor(taskId: string) {
    super(`No task ${taskId} in the local store.`, {
      status: 404,
      remedy:
        "List what is actually there with a2a_list_tasks. An outbound task only appears here " +
        "once a2a_send_message has recorded it; a peer's own task ids are not in this store.",
    });
  }
}

/**
 * A task id arriving from a peer is used as a filename, so it is validated
 * before it ever reaches the filesystem. `../../.ssh/id_rsa` is a task id as far
 * as the wire format is concerned.
 */
export class InvalidTaskIdError extends A2AApiError {
  override readonly name = "InvalidTaskIdError";

  constructor(taskId: string) {
    super(
      `"${taskId}" is not a usable task id: expected 1-128 characters of [A-Za-z0-9._-], ` +
        `and not "." or "..".`,
      {
        status: 400,
        remedy:
          "Task ids are generated by whichever side creates the task; copy one from " +
          "a2a_list_tasks rather than composing it.",
      },
    );
  }
}

/**
 * The shared store cannot be written.
 *
 * This is a THROW AT WRITE TIME, never at construction, and that is the whole
 * point of it existing. Creating the directory eagerly meant an unwritable home —
 * a read-only or sandboxed HOME, an `A2A_STATE_DIR` whose parent does not permit
 * creation — killed the server during startup, which the client reports as a bare
 * "MCP error -32000: Connection closed" with stderr swallowed. The server now
 * comes up, every read answers empty, `a2a_auth_status` reports the directory as
 * unwritable, and only a tool that genuinely needs to write says so.
 */
export class StoreUnwritableError extends A2AApiError {
  override readonly name = "StoreUnwritableError";

  constructor(dir: string, cause: unknown) {
    super(`The task store at ${dir} cannot be written: ${describeCause(cause)}`, {
      status: 0,
      remedy:
        `Create it and make it writable, or point A2A_STATE_DIR somewhere that is. ` +
        `Whatever you choose, the DAEMON must resolve the same path — two directories are ` +
        `two disjoint stores and no task crosses between them.`,
    });
  }
}

/** Thrown when a write path is reached while A2A_ALLOW_WRITES is off. */
export class WritesDisabledError extends Error {
  override readonly name = "WritesDisabledError";

  constructor(what: string) {
    super(
      `${what} is a write operation, but writes are disabled. ` +
        `Set A2A_ALLOW_WRITES=1 to enable the mutating tools.`,
    );
  }
}

/**
 * Turn whatever the A2A SDK threw into an `A2AApiError` carrying a remedy, or
 * return undefined when it is genuinely a connectivity failure.
 *
 * This exists because the SDK's errors carry the status in four different places
 * and sometimes in none, and the cost of guessing wrong is a misleading remedy.
 * The failure this prevents was real and found by a test: a peer answering 401
 * was reported as "check the peer is running", which sends the reader to look at
 * a process that is fine while the actual problem is a token mismatch. The same
 * mistake in reverse cost `mcp-reddit` months of returning HTTP 500 for an
 * invalid bearer token.
 *
 * Four shapes, in the order they are cheapest to recognise:
 *
 *   1. `status` / `statusCode` — the REST transport sets one.
 *   2. `Status: 401` inside the message — the JSON-RPC transport's HTTP path
 *      formats it into prose and keeps no field.
 *   3. `envelopeCode` — a JSON-RPC error envelope, which is what THIS daemon
 *      answers with, so it is the shape a loopback mesh hits most.
 *   4. anything else — a network failure, and the peer really may be down.
 */
export const classifyPeerError = (
  err: unknown,
  peer: string,
  hasToken: boolean,
): A2AApiError | undefined => {
  if (err instanceof A2AApiError) return err;
  if (typeof err !== "object" || err === null) return undefined;

  const status = numeric(err, "status") ?? numeric(err, "statusCode") ?? statusFromMessage(err);
  if (status !== undefined) {
    const remedy = remedyForStatus(status, hasToken);
    return new A2AApiError(`${peer} answered HTTP ${status}: ${messageOf(err)}`, {
      status,
      ...(remedy ? { remedy } : {}),
    });
  }

  const envelopeCode = numeric(err, "envelopeCode");
  if (envelopeCode !== undefined) {
    const remedy = remedyForJsonRpcCode(envelopeCode, hasToken);
    return new A2AApiError(`${peer} refused the request: ${messageOf(err)}`, {
      status: 0,
      ...(remedy ? { remedy } : {}),
      errors: { jsonrpc_code: envelopeCode, ...(reasonOf(err) ? { reason: reasonOf(err) } : {}) },
    });
  }

  return undefined;
};

/**
 * `Status: 401` out of the JSON-RPC transport's prose. Anchored on the SDK's own
 * wording rather than any three digits, so a task id that happens to contain 404
 * is not read as a status.
 */
const statusFromMessage = (err: object): number | undefined => {
  const message = err instanceof Error ? err.message : "";
  const match = /\bStatus:\s*(\d{3})\b/.exec(message);
  return match?.[1] ? Number(match[1]) : undefined;
};

const numeric = (err: object, key: string): number | undefined => {
  const value = (err as Record<string, unknown>)[key];
  return typeof value === "number" ? value : undefined;
};

const reasonOf = (err: object): string | undefined => {
  const value = (err as Record<string, unknown>).reason;
  return typeof value === "string" ? value : undefined;
};

/** The JSON-RPC codes worth a remedy. Our own daemon answers -32001 for auth. */
const remedyForJsonRpcCode = (code: number, hasToken: boolean): string | undefined => {
  if (code === -32001) return remedyForStatus(401, hasToken);
  if (code === -32601) {
    return (
      "The peer does not implement that method. A2A v1.0 renamed every RPC to " +
      "PascalCase (`SendMessage`, `GetTask`) — an 0.x name like `message/send` gets exactly " +
      "this error. Check the peer's card for the protocol version it serves."
    );
  }
  if (code === -32004 || code === -32005) {
    return (
      "The peer does not support that operation. Read its card with a2a_discover_agent: " +
      "`capabilities.streaming` and `push_notifications` are what say which calls it will take."
    );
  }
  if (code === -32602) {
    return (
      "The peer rejected the params. Field names are camelCase on the wire " +
      "(`historyLength`, `pageToken`) because the format is protobuf JSON."
    );
  }
  return undefined;
};

const messageOf = (err: unknown): string => (err instanceof Error ? err.message : String(err));

const describeCause = (cause: unknown): string => {
  if (cause instanceof Error) {
    // fetch() buries the useful half — ECONNREFUSED, ENOTFOUND — in `cause`.
    const inner = (cause as Error & { cause?: unknown }).cause;
    const code = inner instanceof Error ? (inner as Error & { code?: string }).code : undefined;
    return code ? `${cause.message} (${code})` : cause.message;
  }
  return String(cause);
};

/**
 * Status-specific remediation, because the model reads the message and acts on
 * it. A bare "HTTP 401" tells it nothing it can do.
 */
export const remedyForStatus = (status: number, hasToken: boolean): string | undefined => {
  if (status === 401 || status === 403) {
    return hasToken
      ? "The daemon rejected our A2A_TOKEN. Both processes must carry the same value — " +
          "check the LaunchAgent's environment as well as this client's."
      : "The daemon requires a bearer token and A2A_TOKEN is not set here. Set it to the " +
          "same value the daemon was started with.";
  }
  if (status === 404) {
    return (
      "The path exists on no A2A binding. Check the peer's agent card for the URL its " +
      "`supportedInterfaces` actually advertises."
    );
  }
  if (status === 413) {
    return (
      "The request body exceeded the daemon's cap. Send the work as a shorter message and " +
      "put bulk content in a file the other agent can read."
    );
  }
  if (status === 429 || status >= 500) {
    return (
      "Transient — the client already retried with backoff. Try again, and check the " +
      "daemon's stderr if it keeps happening."
    );
  }
  return undefined;
};
